### PR TITLE
Ai production rework

### PR DESCRIPTION
**Pull request by Morlic-fo**

### CODE REVIEW

**Comment by Cjkjvfnby** [comment]
At first review I prefer to review whole diff at once.  Watching by commit usually is not good idea, because if you find something that needs a comment, you need to check if it is not fixed in next commits. 

At current time it is impossible to see(and comment) whole diff by github interface. File contains too many changes.

In this PR cleanups / bugfixes / new features are mixed, whole file is changed.  It is hard to me to understand `1,197 additions, 982 deletions.`.  If you can split it to separate PR it would be great. 

Cleanups like renaming and spaces are good for review, you don't need to know anything about logic. 

Bad thing in separate PR that cleanup request take a lot of time to be merged.

For cleanup commits I always run PyCharm inspector (Code -> Inspect Code). It helps a lot.  Now it mention couple of typos and possible bugs.

**Comment by Cjkjvfnby** [comment]
This comment is not clear for me:
`design_cache = {}  # dict of tuples (rating,pid,designID,cost) sorted by rating and indexed by priority type`

Maybe: `key is priority type and value is list of of tuples (rating, pid, designID, cost) sorted by rating`

Please format comment with same style as python code. With spaces after coma and variables in snake_case.

**Comment by Cjkjvfnby** [comment]
`pr = cProfile.Profile()`

may be move as decorator to utils?  `@profile(sortby='cumulative')`

**Comment by Cjkjvfnby** [comment]
The summary line may be on the same line as the opening quotes or on the next line. [PEP257#multi-line-docstrings](https://www.python.org/dev/peps/pep-0257/#multi-line-docstrings)

Starting from next line looks better for me.

**Comment by Cjkjvfnby** [comment]
`def get_design_cost(design, pid):  # TODO: Use new framework`  this function is not used, do you have any plan for it?

**Comment by Cjkjvfnby** [comment]
`get_best_ship_info`  Not good name for function that returns best design. 

return type looks strange for me `design.id, design, _`  IMHO we can skip design.id

**Comment by Cjkjvfnby** [comment]
It was planned as fix bad variable name and preparation to change `get_best_ship_info` signature:
https://github.com/freeorion/freeorion/pull/427

**Comment by Morlic-fo** [comment]
> At current time it is impossible to see(and comment) whole diff by github interface. File contains too many changes.

Yeah, I probably shouldn't have pushed the cleanup commits when I wanted to get feedback on the ProductionQueueManager in this PR... Probably going to reset this branch to the relevant state...

Anyway, cleaning up ProductionAI is a nightmare. Fixing whitespace alone means more than github is willing to show...

**Comment by Cjkjvfnby** [comment]
I hope you use IDE refactoring tools for cleanups: rename variable, find usage, static analysis. It really save a lot of time.  
PS use add `?w=1` to url if you want ignore whitespace changes.

**Comment by Cjkjvfnby** [comment]
This feature called unpacking

``` python
for design_stats in best_designs:
    top_rating, pid, top_id, cost = design_stats
```

It saves some lines and variables

``` python
for top_rating, pid, top_id, cost in best_designs:
```

**Comment by Cjkjvfnby** [comment]
``` python
valid_locs = [item[1] for item in best_designs if item[0] == top_rating and item[2] == top_id]
```

Named constant are more readable then list indexies

``` python
valid_locs = [loc for best_rating, loc, best_design, _ in best_designs if best_rating == top_rating and best_design == top_id]
```

**Comment by Cjkjvfnby** [comment]
`def get_best_ship_info`

If there is no planet that can produce any of designs. You will get design with worst rating and locations where it can be built (not location you asked for). 

You can fix it by `else` statement.

```
for design_stats in best_designs:
    top_rating, pid, top_id, cost = design_stats
    if pid in planet_ids:
        break
else:
   return None, None, None
```

**Comment by Dilvish-fo** [comment]
Heya, sorry I didn't get you any comments before you closed it out; I've been just too busy lately.  For the quick glance I was able to take right now, the only comment I'd have is that in FreeOrionAI, the action list call to foAIstate.production_queue_manager.update_for_new_turn should probably come after the universe survey, it seems to me.

**Comment by Morlic-fo** [comment]
No problem.

There are quite some things in this branch that were experimental and I do not like them too much anymore. The core and interesting stuff is very much hidden in the ProductionAI 3000+ line changes so once I figure out what I think is worth keeping, I will open a cleaner PR / branch...

So... don't waste any time on reading through this PR.

**Pull request closed without merging**
